version: '3.4'

networks:
  rederefit:
      driver: bridge
      ipam:
          driver: default
          config:
              - subnet: "172.18.0.0/16"


services:

      sqlserver:
            container_name: sqlserver
            hostname: hostsqlserver
            image: "mcr.microsoft.com/mssql/server:2022-latest"   
            volumes:
               - F:\Projetos\DockerMicroservices\volumes:/var/opt/mssql/data
            ports:
              - 1433:1433
            expose:
              - 1433
            environment:
               ACCEPT_EULA: 'Y'
               MSSQL_SA_PASSWORD : 'cadastroprodutos123!'
               MSSQL_PID : 'Developer'
            networks:
               rederefit:
                ipv4_address: 172.18.0.6


      mssqltools:
            image: mcr.microsoft.com/mssql-tools
            depends_on:
             - sqlserver
            volumes:
             - F:\Projetos\DockerMicroservices\CriarBancoEstoque.sql:/tmp/CriarBancoEstoque.sql  
            command: /bin/bash -c "sleep 70 && /opt/mssql-tools/bin/sqlcmd -S sqlserver -U SA -P cadastroprodutos123! -d master -i /tmp/CriarBancoEstoque.sql"
            networks:
              rederefit:
               ipv4_address: 172.18.0.7


      apirefit:
       image: api-refit
       container_name: apiRefit
       build:
         context: .
         dockerfile: APIRefit\Dockerfile
       ports:
       - "5000:5000"
       depends_on:
         - sqlserver
       networks:
         rederefit:
          ipv4_address: 172.18.0.4

    