version: '3.4'

networks:
  redemicrosservices:
      driver: bridge
      ipam:
          driver: default
          config:
              - subnet: "172.18.0.0/16"


services:

      sqlserver:
            container_name: sqlserver
            hostname: hostsqlserver
            image: "mcr.microsoft.com/mssql/server:2022-latest"   
            volumes:
               - ./volumes:/var/opt/mssql/data
            ports:
              - 1433:1433
            expose:
              - 1433
            environment:
               ACCEPT_EULA: 'Y'
               MSSQL_SA_PASSWORD : 'microservicos123!'
               MSSQL_PID : 'Developer'
            networks:
               redemicrosservices:
                ipv4_address: 172.18.0.6


      rabbitmq: 
            container_name: rabbitmq
            image: "rabbitmq:3-management" 
            ports: 
               - "5672:5672" 
               - "15672:15672"
            environment: 
              RABBITMQ_DEFAULT_USER: 'adm' 
              RABBITMQ_DEFAULT_PASS: '123'
            networks: 
              redemicrosservices: 
                ipv4_address: 172.18.0.9

      apiusers:
            container_name: apiusers
            image: api-users
            build:
              context: .
              dockerfile: UserService\UserService.WebApi\Dockerfile
            ports:
            - "5020:5020"
            depends_on:
            - sqlserver
            networks:
             redemicrosservices:
              ipv4_address: 172.18.0.7

      apiauth:
            container_name: apiauth
            image: api-auth
            build:
              context: .
              dockerfile: AuthenticationService\AuthenticationService.WebApi\Dockerfile
            ports:
            - "5030:5030"
            depends_on:
            - apiusers
            networks:
             redemicrosservices:
              ipv4_address: 172.18.0.8


      rpamercadolivre:
            container_name: rpamercadolivre
            image: console-rpamercadolivre
            build:
              context: .
              dockerfile: RPAMercadoLivreService\RPAMercadoLivre.Console\Dockerfile
            depends_on:
            - rabbitmq
            networks:
              redemicrosservices:
               ipv4_address: 172.18.0.10
            entrypoint: ["sh", "-c", "until nc -z rabbitmq 5672; do echo 'Aguardando RabbitMQ...'; sleep 5; done; dotnet RPAMercadoLivre.Console.dll"]

    