version: '3.4'

services:
  apiproduct:
    container_name: apiproduct
    image: api-product
    build:
      context: .
      dockerfile: ProductService\ProductService.WebApi\Dockerfile
    ports:
    - "5010:5010"
    depends_on:
    - sqlserver
    - rabbitmq
    networks:
        redemicrosservices:
         ipv4_address: 172.18.0.5
    entrypoint: ["sh", "-c", "until nc -z rabbitmq 5672; do echo 'Aguardando RabbitMQ...'; sleep 5; done; dotnet ProductService.WebApi.dll"]
