version: '3.4'

volumes:
      produtosdata:

networks:
       apirest:    
       backend:    
   
services:

      sqlserver:
            image: "mcr.microsoft.com/mssql/server:2022-latest"   
            volumes:
               - produtosdata:/var/opt/mssql
            networks:
              - backend
            environment:
              - 'ACCEPT_EULA=SIM'
              - 'MSSQL_SA_PASSWORD=123'
              - 'MSSQL_PID=Developer'
      apirefit:
       build:
         context: .
         dockerfile: Dockerfile
       networks:
           - backend
       ports:
         - 5000:80
       environment:
          - DHOST=sqlserver
       depends_on:
          - sqlserver

    