version: '3.4'

services:

  cadastroproduto:
    image: api-cadastroproduto
    container_name: cadastroProduto
    build:
      context: .
      dockerfile: CadastroProduto\Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:80"
      - "8081:443"
    expose:
      - 8080
    networks:
      - local
    depends_on:
      - sqlserver