version: '3.4'

networks:
  local:
    name: local       

services:

      sqlserver:
            container_name: sqlserver
            image: "mcr.microsoft.com/mssql/server:2022-latest"   
            volumes:
               - .\volumes:/var/opt/mssql
               - .\CriarBancoEstoque.sql:/scripts/            
            command: /bin/bash -c "sleep 30 && /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P '123' -d master -i /scripts/CriarBancoEstoque.sql"
            networks:
              - local
            ports:
              - 1433:1433
            expose:
              - 1433
            environment:
               ACCEPT_EULA: 'Y'
               MSSQL_SA_PASSWORD : '123'
               MSSQL_PID : 'Developer'

      apirefit:
       image: api-refit
       container_name: apiRefit
       build:
         context: .
         dockerfile: APIRefit\Dockerfile
       networks:
         - local
       ports:
         - 5000:5000
       expose:
         - 5000
       environment:
         - ASPNETCORE_ENVIRONMENT=Development 
       depends_on:
         - sqlserver

    