version: '3.4'

networks:
  rederefit:
      driver: bridge
      ipam:
          driver: default
          config:
              - subnet: "172.18.0.0/16"


services:

      sqlserver:
            container_name: sqlserver
            hostname: hostsqlserver
            image: "mcr.microsoft.com/mssql/server:2022-latest"   
            volumes:
               - ./volumes:/var/opt/mssql/data
            ports:
              - 1433:1433
            expose:
              - 1433
            environment:
               ACCEPT_EULA: 'Y'
               MSSQL_SA_PASSWORD : 'microservicos123!'
               MSSQL_PID : 'Developer'
            networks:
               rederefit:
                ipv4_address: 172.18.0.6


      rabbitmq: 
            container_name: rabbitmq
            image: "rabbitmq:3-management" 
            ports: 
               - "5672:5672" 
               - "15672:15672"
            environment: 
              RABBITMQ_DEFAULT_USER: 'adm' 
              RABBITMQ_DEFAULT_PASS: '123'
            networks: 
              rederefit: 
                ipv4_address: 172.18.0.9

      apiusuarios:
            container_name: apiUsuarios
            image: api-usuarios
            build:
              context: .
              dockerfile: ServiceUsuarios\Usuarios\Dockerfile
            ports:
            - "5020:5020"
            depends_on:
            - sqlserver
            networks:
             rederefit:
              ipv4_address: 172.18.0.7

      apiautenticacao:
            image: api-autenticacao
            container_name: apiAutenticacao
            build:
              context: .
              dockerfile: ServiceAutenticacao\Autenticacao\Dockerfile
            ports:
            - "5030:5030"
            depends_on:
            - apiusuarios
            networks:
             rederefit:
              ipv4_address: 172.18.0.8

      apirefit:
            image: api-refit
            container_name: apiRefit
            build:
              context: .
              dockerfile: ServiceCadastroProdutoRefit\APIRefit\Dockerfile
            ports:
            - "5000:5000"
            depends_on:
            - cadastroproduto
            networks:
              rederefit:
               ipv4_address: 172.18.0.4

      consoleapp:
            image: console-rpamercadolivre
            container_name: rpaMercadoLivre
            build:
              context: .
              dockerfile: ServiceRPAMercadoLivre\RPAMercadoLivre\Dockerfile
            depends_on:
            - rabbitmq
            networks:
              rederefit:
               ipv4_address: 172.18.0.10

    