// <auto-generated />
using System;
using CadastroProduto.AcessoDados.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CadastroProduto.AcessoDados.Migrations
{
    [DbContext(typeof(ProdutoDbContext))]
    [Migration("20241123194317_RemoverCamposDesnecessarios")]
    partial class RemoverCamposDesnecessarios
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CadastroProduto.Dominio.Entidades.Produto", b =>
                {
                    b.Property<int>("idproduto")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(1, 1)
                        .HasColumnType("int")
                        .HasColumnName("idproduto");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idproduto"));

                    b.Property<string>("nmproduto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("nmproduto");

                    b.Property<decimal?>("nuValorAmazon")
                        .HasPrecision(16, 2)
                        .HasColumnType("decimal(16,2)")
                        .HasColumnName("nuvalorAmazon");

                    b.Property<decimal?>("nuValorMercadoLivre")
                        .HasPrecision(16, 2)
                        .HasColumnType("decimal(16,2)")
                        .HasColumnName("nuvalorMercadoLivre");

                    b.Property<decimal>("nuvalor")
                        .HasPrecision(16, 2)
                        .HasColumnType("decimal(16,2)")
                        .HasColumnName("nuvalor");

                    b.HasKey("idproduto");

                    b.ToTable("Produtos", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
